# Generated by Django 4.2 on 2023-04-05 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treemenu', '0002_menu_head'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='head',
            new_name='menu_name',
        ),
    ]
